name: Dependency Review
on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - "**/*.md"

jobs:
  dependency-review:
    name: Dependencies Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false
    - name: Dependency Review
      uses: actions/dependency-review-action@a6993e2c61fd5dc440b409aa1d6904921c5e1894 # v4.3.5
      with:
        fail-on-scopes: runtime,unknown
        comment-summary-in-pr: on-failure
