name: Publish

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: '24.x'
        check-latest: true
        registry-url: 'https://registry.npmjs.org'
    - name: Download Build Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: build
        path: dist
    - name: Publish
      run: npm publish --access public
