name: PR on Main

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: micro-lc/middleware/.github/workflows/tests.yml@public-path
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: micro-lc/middleware/.github/workflows/lint.yml@public-path

  build:
    uses: micro-lc/middleware/.github/workflows/build.yml@public-path
