name: Tests

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: .nvmrc
        check-latest: true
    - name: Install Dependencies
      run: |
        npm ci
        npm run build:cli

    - name: Run Unit Tests
      run: npm run coverage

    - name: Run CLI Tests
      run: npm run test:cli

    - name: Collect Coveralls coverage
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      continue-on-error: true
      with:
        github-token: ${{ secrets.token }}
        path-to-lcov: './coverage/lcov.info'
